import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/nav';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fit People Cook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-red-500 min-h-screen">
        <Nav />
        <h1 className="text-center text-3xl font-extrabold">Fit People Cook</h1>
      </main>
    </div>
  );
};

export default Home;
